# Generated by Django 4.2.1 on 2023-06-11 19:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de categoría')),
                ('nombreCategoria', models.CharField(max_length=80, verbose_name='Nombre de la categoría')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='ID Producto')),
                ('nombreProducto', models.CharField(max_length=80, verbose_name='Marca vehículo')),
                ('descripcionProducto', models.CharField(blank=True, max_length=80, null=True, verbose_name='Modelo')),
                ('precioProducto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descuento_subscriptor', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('descuento_oferta', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('imagenProducto', models.ImageField(default='sinfoto.jpg', upload_to='static/images/', verbose_name='Imagen')),
                ('categoriaProducto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.categoriaproducto')),
            ],
        ),
    ]
