# Generated by Django 4.2.1 on 2023-06-11 19:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoriaProducto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.categoriaproducto', verbose_name='Categoria Producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcionProducto',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Descripcion Producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descuento_oferta',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Desc. Oferta'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descuento_subscriptor',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Desc. Subscriptor'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagenProducto',
            field=models.ImageField(default='sinfoto.jpg', upload_to='static/images/', verbose_name='Imagen Producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombreProducto',
            field=models.CharField(max_length=80, verbose_name='Nombre Producto'),
        ),
    ]
