# Generated by Django 4.2.1 on 2023-06-12 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_producto_categoriaproducto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='estadoProducto',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de categoría')),
                ('nombreEstado', models.CharField(max_length=80, verbose_name='Nombre del estado')),
            ],
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagenProducto',
            field=models.ImageField(default='sinfoto.jpg', upload_to='images/', verbose_name='Imagen Producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precioProducto',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Producto'),
        ),
    ]
