# Generated by Django 4.2.1 on 2023-06-12 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_estadoproducto_alter_producto_imagenproducto_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='estadoProducto',
        ),
    ]
