# Generated by Django 4.2.1 on 2023-06-12 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_delete_estadoproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='cantidad',
            field=models.IntegerField(default=1, verbose_name='Cantidad Producto'),
        ),
    ]
