# Generated by Django 4.2.1 on 2023-06-12 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_producto_cantidad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='cantidad',
            new_name='cantidadProducto',
        ),
        migrations.AddField(
            model_name='producto',
            name='disponibilidadProducto',
            field=models.CharField(choices=[('1', 'Disponible en bodega'), ('2', 'Agotado'), ('3', 'En oferta')], default='1', max_length=1, verbose_name='Disponibilidad'),
        ),
    ]
