# Generated by Django 4.2.2 on 2023-06-14 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_cantidad_producto_cantidadproducto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoriaproducto',
            name='idCategoria',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='idProducto',
        ),
        migrations.AddField(
            model_name='categoriaproducto',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
