# Generated by Django 4.2.2 on 2023-06-16 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_categoriaproducto_idcategoria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='cantidadProducto',
        ),
        migrations.AlterField(
            model_name='producto',
            name='disponibilidadProducto',
            field=models.CharField(choices=[('1', 'Disponible en bodega'), ('2', 'Agotado'), ('3', 'En oferta')], max_length=1, verbose_name='Disponibilidad Producto'),
        ),
    ]
