# Generated by Django 4.2.2 on 2023-06-16 22:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_producto_cantidadproducto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='descuento_subscriptor',
        ),
        migrations.AddField(
            model_name='producto',
            name='descSubscriptor',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Desc. Subscriptor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producto',
            name='descuento_oferta',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Desc. Oferta'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precioProducto',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Precio Producto'),
        ),
    ]
