# Generated by Django 4.2.2 on 2023-06-22 21:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_categoriaproducto_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Bodega',
                'verbose_name_plural': 'Bodegas',
                'db_table': 'Bodega',
            },
        ),
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('nro_boleta', models.IntegerField(primary_key=True, serialize=False, verbose_name='Nro boleta')),
                ('monto_sin_iva', models.IntegerField(verbose_name='Monto sin IVA')),
                ('iva', models.IntegerField(verbose_name='IVA')),
                ('total_a_pagar', models.IntegerField(verbose_name='Total a pagar')),
                ('fecha_venta', models.DateField(verbose_name='Fecha de venta')),
                ('fecha_despacho', models.DateField(blank=True, null=True, verbose_name='Fecha de despacho')),
                ('fecha_entrega', models.DateField(blank=True, null=True, verbose_name='Fecha de entrega')),
                ('estado', models.CharField(choices=[('Anulado', 'Anulado'), ('Vendido', 'Vendido'), ('Despachado', 'Despachado'), ('Entregado', 'Entregado')], max_length=50, verbose_name='Estado')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.perfil')),
            ],
            options={
                'verbose_name': 'Boleta',
                'verbose_name_plural': 'Boletas',
                'db_table': 'Boleta',
            },
        ),
        migrations.CreateModel(
            name='DetalleBoleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.IntegerField(verbose_name='Precio')),
                ('descuento_subscriptor', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Descto subs')),
                ('descuento_oferta', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Descto oferta')),
                ('descuento_total', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Descto total')),
                ('descuentos', models.IntegerField(verbose_name='Descuentos')),
                ('precio_a_pagar', models.IntegerField(verbose_name='Precio a pagar')),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.bodega')),
                ('boleta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.boleta')),
            ],
            options={
                'verbose_name': 'Detalle de boleta',
                'verbose_name_plural': 'Detalles de boletas',
                'db_table': 'DetalleBoleta',
            },
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.IntegerField(verbose_name='Precio')),
                ('descuento_subscriptor', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Descto subs')),
                ('descuento_oferta', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Descto oferta')),
                ('descuento_total', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Descto total')),
                ('descuentos', models.IntegerField(verbose_name='Descuentos')),
                ('precio_a_pagar', models.IntegerField(verbose_name='Precio a pagar')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.perfil')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.producto')),
            ],
            options={
                'verbose_name': 'Carrito de compras',
                'verbose_name_plural': 'Carritos de compras',
                'db_table': 'Carrito',
                'ordering': ['cliente', 'producto'],
            },
        ),
    ]
