# Generated by Django 4.2.2 on 2023-06-22 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_bodega_boleta_detalleboleta_carrito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='disponibilidadProducto',
        ),
    ]
