# Generated by Django 4.2.2 on 2023-06-22 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_producto_disponibilidadproducto'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategoriaProducto',
            new_name='Categoria',
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['nombre'], 'verbose_name': 'Categoría de producto', 'verbose_name_plural': 'Categorías de productos'},
        ),
        migrations.RenameField(
            model_name='categoria',
            old_name='nombreCategoria',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='categoriaProducto',
            new_name='categoria',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='descripcionProducto',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='imagenProducto',
            new_name='imagen',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='nombreProducto',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='precioProducto',
            new_name='precio',
        ),
    ]
