# Generated by Django 4.2.2 on 2023-06-22 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_categoriaproducto_categoria_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='descSubscriptor',
            new_name='descuento_subscriptor',
        ),
    ]
