# Generated by Django 4.2.2 on 2023-07-07 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_perfilusuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PerfilUsuario',
        ),
    ]
