# Generated by Django 4.2.2 on 2023-07-08 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_delete_perfilusuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='usuario',
            new_name='user',
        ),
    ]
