# Generated by Django 4.2.2 on 2023-07-11 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_rename_usuario_perfil_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='user',
            new_name='usuario',
        ),
    ]
