# Generated by Django 5.0.4 on 2024-05-24 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_categoria_options_alter_producto_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['nombre'], 'verbose_name': 'Categoría de producto', 'verbose_name_plural': 'Categorías de productos'},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['categoria', 'nombre'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterField(
            model_name='perfil',
            name='tipo_usuario',
            field=models.CharField(choices=[('Cliente', 'Cliente'), ('Administrador', 'Administrador'), ('Superusuario', 'Superusuario')], max_length=50, verbose_name='Tipo de usuario'),
        ),
        migrations.AlterModelTable(
            name='bodega',
            table='Bodega',
        ),
        migrations.AlterModelTable(
            name='boleta',
            table='Boleta',
        ),
        migrations.AlterModelTable(
            name='carrito',
            table='Carrito',
        ),
        migrations.AlterModelTable(
            name='categoria',
            table='Categoria',
        ),
        migrations.AlterModelTable(
            name='detalleboleta',
            table='DetalleBoleta',
        ),
        migrations.AlterModelTable(
            name='perfil',
            table='Perfil',
        ),
        migrations.AlterModelTable(
            name='producto',
            table='Producto',
        ),
    ]
